plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

android {
    namespace 'com.example.kotlin.dict_content_provider_common'
    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility rootProject.ext.sourceCompatibility
        targetCompatibility rootProject.ext.targetCompatibility
    }
    kotlinOptions {
        jvmTarget = rootProject.ext.jvmTarget
    }
}

dependencies {
    implementation platform(libs.kotlin.bom)
    implementation libs.androidx.ktx

    testImplementation libs.test.junit

    androidTestImplementation libs.androidTest.junit
    androidTestImplementation libs.androidTest.espressoCore
}