# print current branch name
current_branch=$(git symbolic-ref --short head)
echo "current branch is $current_branch"

isEnableRunUnitTest = 1
if [ $isEnableRunUnitTest -eq 1]; then
    echo "start running unit test"
    cmd = "./gradlew :app:testDebugUnitTest"
    echo "end running unit test"
 fi
 exit 0